server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/springboot/protocol/openid-connect/certs
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee_service
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
        - id: department_service
          uri: http://localhost:8082
          predicates:
            - Path=/departments/**
keycloak:
  realm: springboot
  auth-server-url: http://localhost:8080
  resource: springboot-client
  credentials:
    secret: tgertet777
  bearer-only: true
