server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
keycloak:
  realm: springboot
  auth-server-url: http://localhost:8080
  resource: spring-boot
  credentials:
    secret: ruyru6u676ru
  bearer-only: true
  security-constraints:
    - auth-roles:
        - user
      security-collections:
        - patterns:
            - /employees/**
